spring:
  cloud:
    skipper:
      server:
        package-repositories:
          experimental:
            name: experimental
            url: "http://skipper-repository.cfapps.io/repository/experimental"
            description: "Experimental Skipper Repository"