kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: scdf-rb
subjects:
- kind: ServiceAccount
  name: scdf-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: scdf-role
  apiGroup: rbac.authorization.k8s.io
